version: 0.1
phases:
  install:
    commands:
      - env
      # - aws cloudformation package --template-file ingest-handler.yaml --s3-bucket build-artifacts.jammm.com --output-template-file output.yaml
artifacts:
  type: zip
  files:
    - output.yaml
